version: '3.4'

services:
  cryptotracker:
    image: crypto_tracker
    build:
      context: .
      dockerfile: ./Docker_Files/Python
    network_mode: host
    depends_on:
      - "mongodb"
    restart: always
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongodb:
    image: mongo_db
    build:
      context: .
      dockerfile: ./Docker_Files/Mongo
    ports:
      - "27017:27017"
    restart: always
    command:
        - '-f'
        - '/etc/mongod.conf'
    volumes:
        - '/home/ec2-user/crypto_tracker/mongod.conf:/etc/mongod.conf'
