version: '3.4'

services:
  cryptotracker:
    image: crypto_tracker
    container_name: crypto_tracker
    build:
      context: .
      dockerfile: ./Docker_Files/Python
    network_mode: host
    depends_on:
      - "mongodb"
    restart: always
    volumes:
      - '/home/ec2-user/iftt_api_key:/iftt'

  mongodb:
    image: mongo_db
    container_name: mongo_db
    build:
      context: .
      dockerfile: ./Docker_Files/Mongo
    ports:
      - "59999:27017"
    restart: always
    command:
        - '-f'
        - '/etc/mongod.conf'
        - --auth
    volumes:
        - '/home/ec2-user/crypto_tracker/mongod.conf:/etc/mongod.conf'
        - '/home/ec2-user/mongodbdata:/data/db'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
        
